# Generated by Django 5.0.6 on 2024-06-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambita_python', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='usuario',
            field=models.ForeignKey(default='ssssss', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
